site_name: HKI Elements Card Suite Documentation
site_url: https://jimz011.github.io/hki-elements/
repo_url: https://github.com/jimz011/hki-elements/
repo_name: jimz011/hki-elements
theme:
  name: material
nav:
  - Home: source/index.md
  - Installation: source/installation.md
  - Cards:
      - HKI Header Card:
          - Overview: cards/hki-header-card/index.md
          - Examples: cards/hki-header-card/examples.md
      - HKI Navigation Card:
          - Overview: cards/hki-navigation-card/index.md
          - Examples: cards/hki-navigation-card/examples.md
      - HKI Button Card:
          - Overview: cards/hki-button-card/index.md
          - Examples: cards/hki-button-card/examples.md
      - HKI PostNL Card:
          - Overview: cards/hki-postnl-card/index.md
          - Examples: cards/hki-postnl-card/examples.md
      - HKI Notification Card:
          - Overview: cards/hki-notification-card/index.md
          - Examples: cards/hki-notification-card/examples.md
      - HKI Notify (Custom Component):
          - Overview: components/hki-notify/index.md
  - Troubleshooting: source/troubleshooting.md
  - Changelog: source/changelog.md
